name: Open Pull Request on Sync Branch Change

on:
  push:
    # branches-ignore:
    #   - master
    branches:
      - sincrono

jobs:
  open_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Create Pull Request
        uses: vsoch/pull-request-action@1.1.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_TITLE: ${{ steps.extract_branch.outputs.branch}}
