name: Sync Changes

on:
  pull_request:
    types: ['closed']
    branches:
      - master  # Substitua pela branch que deseja monitorar

jobs:
  sync_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
      
      - name: Clear
        run: |
          rm -rf temp
          rm -rf destino

      - name: Clone repositorio v4
        run: |
          git clone https://github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git destino
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          

      - name: Clone repositori v5
        run: |
          git clone https://github.com/ARPDev-Desenvolvimento/init-react-vite-v5.git temp
          cd temp
          rm -rf .git
          rm -rf .env
          rm -rf config
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Copy
        run: cp -rf destino/* temp/

      - name: Push 
        run: |
          cd destino
          git config --local user.name "ARPDev-Desenvolvimento"
          git config --local user.email "arpdevdesenvolvimento@gmail.com"
          git add .
          git commit -m "Sua mensagem de commit aqui"
          git push https://${{secrets.TOKEN}}@github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git master

      # - name: Clone destination repository
      #   run: git clone https://github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git temp
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # - name: Commit and push changes
      #   run: |
      #     git config --local user.name "ARPDev-Desenvolvimento"
      #     git config --local user.email "arpdevdesenvolvimento@gmail.com"
      #     git add .
      #     git commit -m "Sync changes from pull request"
      #     git push https://${{secrets.TOKEN}}@github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git master

      # - name: Sync changes to another repository
      #   run: |
      #     cd destino
      #     git remote add destino https://github.com/ARPDev-Desenvolvimento/init-react-vite-v5.git
      #     git push destino master

      # - name: Print Secret Value
      #   run: |
      #     echo "O valor da minha secret é: ${{ secrets.TOKEN }}"
      
      # - name: Clone repository with access token
      #   run: |
      #     git clone https://github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git temp
      #     cp -r temp/. .
      #   env:
      #     TOKEN: ${{ secrets.TOKEN }}

      # - name: Pull changes from remote repository
      #   run: |
      #     git pull origin master

      # - name: Commit and push changes
      #   run: |
      #     git config --local user.name "ARPDev-Desenvolvimento"
      #     git config --local user.email "arpdevdesenvolvimento@gmail.com"
      #     git add .
      #     git commit -m "Sync changes from first repository"
      #     git push https://${{secrets.TOKEN}}@github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git master
      
      # - name: Remove temporary directory
      #   run: |
      #     rm -rf temp
      #     rm -rf destino

