name: Repository synchronization

on:
  pull_request:
    types: ['closed']
    branches:
      - master

jobs:
  sync_changes:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'ARPDev-Desenvolvimento'
          git config --global user.email 'arpdevdesenvolvimento@gmail.com'

      - name: Get PR metadata
        id: pr_metadata
        run: |
          PR_TITLE=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
          PR_DESCRIPTION=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
          PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
          echo "::set-output name=title::$PR_TITLE"
          echo "::set-output name=description::$PR_DESCRIPTION"
          echo "::set-output name=number::$PR_NUMBER"

      - name: clone v5
        run: git clone https://github.com/ARPDev-Desenvolvimento/init-react-vite-v5.git temp
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
      - name: clone v4
        run: git clone https://github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git destino
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: clean
        run: rm -rf destino/src/*
      
      - name: copy
        run: cp -rf temp/src/* destino/src

      - name: create branch
        run: |
          cd destino/
          git config --local user.name "ARPDev-Desenvolvimento"
          git config --local user.email "arpdevdesenvolvimento@gmail.com"
          git checkout -b sincrono
          git add .
          git commit -m "Synchronized changes from pull request ${{ steps.pr_metadata.outputs.number }}: ${{ steps.pr_metadata.outputs.title }}"
          git pull origin sincrono
          git push https://${{secrets.TOKEN}}@github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git sincrono
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # - name: Open Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     commit-message: ${{ steps.pr_metadata.outputs.description }}
      #     title: ${{ steps.pr_metadata.outputs.title }}
      #     body: Pull request description
      #     branch: feature/${{ steps.pr_metadata.outputs.number }}
      #     base: master
      #     repository: ARPDev-Desenvolvimento/init-react-vite-v4
      #     delete-branch: true

      # - name: Extract Branch Name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch

      # - name: Create Pull Request
      #   uses: vsoch/pull-request-action@1.1.0
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #     PULL_REQUEST_BRANCH: "master"
      #     PULL_REQUEST_TITLE: ${{ steps.extract_branch.outputs.branch}}

      - name: clear arquivo
        run: |
          rm -rf temp destino