name: Sync Changes

on:
  pull_request:
    types: ['closed']
    branches:
      - master  # Substitua pela branch que deseja monitorar

jobs:
  sync_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Get PR metadata
        id: pr_metadata
        run: |
          PR_TITLE=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
          PR_DESCRIPTION=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
          PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
          echo "::set-output name=title::$PR_TITLE"
          echo "::set-output name=description::$PR_DESCRIPTION"
          echo "::set-output name=number::$PR_NUMBER"

      - name: clone v5
        run: git clone https://github.com/ARPDev-Desenvolvimento/init-react-vite-v5.git temp
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
      - name: clone v4
        run: git clone https://github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git destino
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: clean
        run: rm -rf destino/src/*
      
      - name: copy
        run: cp -rf temp/src/* destino/src

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: "Synchronized changes from pull request ${{ steps.pr_metadata.outputs.number }}: ${{ steps.pr_metadata.outputs.title }}"
          title: "Synchronized changes from pull request ${{ steps.pr_metadata.outputs.number }}: ${{ steps.pr_metadata.outputs.title }}"
          body: "Changes from pull request ${{ steps.pr_metadata.outputs.number }}:\n${{ steps.pr_metadata.outputs.description }}"

      # - name: push
      #   run: |
      #     cd destino/
      #     git config --local user.name "ARPDev-Desenvolvimento"
      #     git config --local user.email "arpdevdesenvolvimento@gmail.com"
      #     git add .
      #     git commit -m "Synchronized changes from pull request ${{ steps.pr_metadata.outputs.number }}: ${{ steps.pr_metadata.outputs.title }}"
      #     git push https://${{secrets.TOKEN}}@github.com/ARPDev-Desenvolvimento/init-react-vite-v4.git master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: clear arquivo
        run: |
          rm -rf temp destino